#Â Build and run tests under Travis CI

# Defaults so need not specify in linux jobs
os: linux
dist: focal  # has Python 3.8 as default "python" command

language: java

jobs:
  include:

    - name: "openjdk11 on Linux"
      jdk: openjdk11
 
    # Installed Gradle/Groovy limits us to Java 15.
    # Unsupported class file major version 60 (on Java 16).
    - name: "openjdk15 on Linux"
      jdk: openjdk15

# No installation, but check versions here
install:
  # Confirm versions and paths (this has been a problem)
  - echo $PATH
  - java -version
  - which python
  - python -V
  - ./gradlew --version


# Cache artefacts downloaded by Gradle
# https://guides.gradle.org/executing-gradle-builds-on-travisci/#enable_caching_of_downloaded_artifacts
# (Caching may be flakey on Windows.)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


# Run the build only on the latest run-time approach
script:
  - ./gradlew --no-daemon rt3:test
